### ISSUE TITLE
Library Issue

### ISSUE THREAD

**Issue by utkarsh027** [chenyongrowan/scTIGER#1]
There is a issue regarding library conflict. So please can You rerun the sctiger and let me know the exact cause of error, after inflating the data step.

**Comment by chenyongrowan** [comment]
Hi! Can you please send the list of packages installed for your scTIGER environment? If you installed scTIGER using the installation instructions in our [README.md](https://github.com/chenyongrowan/scTIGER/blob/main/README.md) file, you can get this by typing conda list -n scTIGER. 


Some of the packages may have been updated. We provide the version for each package on our installation in the prerequisites section of our [README.md](https://github.com/chenyongrowan/scTIGER/blob/main/README.md) file. If you specify each package to match the version we are using, it should run without error.

**Comment by utkarsh027** [comment]
Ok i will do it today

**Comment by utkarsh027** [comment]
I used same packages as in Readme but there was conflict between numpy and
bambi

**Comment by chenyongrowan** [comment]
I see what happened. Pytorch released new versions and it is forcing certain packages to update which becomes incompatible with Bambi. I was just able to install scTIGER on my CPU processing machine with the following commands: 

conda create -n scTIGER python=3.9.2
conda activate scTIGER
conda install pytorch==2.1.2 torchvision==0.16.2 torchaudio==2.1.2 cpuonly==2.0 conda-forge::fsspec -c pytorch
pip install pandas==1.4.3 matplotlib==3.8.2 networkx==3.1 argparse==1.4.0 scipy==1.11.4 scanpy==1.9.6 leidenalg==0.10.1 bambi==0.9.0 arviz==0.16.1 pyarrow numba==0.56.4
export MKL_THREADING_LAYER=GNU
conda install numpy==1.22.0

The below file has the commands as shown above and the packages that resulted from that installation. 
[scTIGER_PackageVersionsALL.txt](https://github.com/chenyongrowan/scTIGER/files/15154025/scTIGER_PackageVersionsALL.txt)


Please let me know if the dependency issue still appears on your end.

**Comment by utkarsh027** [comment]
Hi,
I tried but this error is coming(attaching) , i followed every step .

**Comment by chenyongrowan** [comment]
Can you please provide the error message you are seeing? I don't see anything attached to the last comment. It would be most helpful to have the commands and output you are getting from the command line. You can type "script" in the command line before running the above commands and it will provide a text file with this information that I can review.

**Comment by utkarsh027** [comment]
I have attached the screenshot in the last email.
Also I will send You the script by today.

**Comment by chenyongrowan** [comment]
I cannot see the screenshot in your reply on the thread. It may be that email attachments do not appear with the responses when replying via email. Can you please attach the screenshot and script to a response directly in the thread for documentation of the issue for others who may be experiencing a similar issue? Thank you!

**Comment by utkarsh027** [comment]
the error is this after following all steps-

(scTIGER) ***@***.*** SCTIGER % cd SCTIGER

(scTIGER) ***@***.*** SCTIGER % chmod +x run_scTIGER.py

(scTIGER) ***@***.*** SCTIGER % unzip
Data/ProstateCancer/Patient4_Benign_endothelial.zip -d
./Data/ProstateCancer/

Archive:  Data/ProstateCancer/Patient4_Benign_endothelial.zip

  inflating: ./Data/ProstateCancer/Patient4_Benign_endothelial.csv

(scTIGER) ***@***.*** SCTIGER % ./run_scTIGER.py -goi
AR+PTEN+ERG -ctrl ./Data/ProstateCancer/Patient4_Benign_endothelial.csv
-exp ./Data/ProstateCancer/Patient4_Tumor_endothelial.csv -p 50 -top 100
-zero 0.15 -o SampleResult_ProstateCancer

Traceback (most recent call last):

  File "/Users/utkarsh/scTIGER/scTIGER/./run_scTIGER.py", line 14, in
<module>

    import scTIGER as sd

  File "/Users/utkarsh/scTIGER/scTIGER/scTIGER.py", line 12, in <module>

    import bambi as bmb

  File
"/Users/Shared/anaconda3/envs/scTIGER/lib/python3.9/site-packages/bambi/__init__.py",
line 3, in <module>

    from pymc import math

  File
"/Users/Shared/anaconda3/envs/scTIGER/lib/python3.9/site-packages/pymc/__init__.py",
line 52, in <module>

    from pymc import gp, ode, sampling

  File
"/Users/Shared/anaconda3/envs/scTIGER/lib/python3.9/site-packages/pymc/gp/__init__.py",
line 15, in <module>

    from pymc.gp import cov, mean, util

  File
"/Users/Shared/anaconda3/envs/scTIGER/lib/python3.9/site-packages/pymc/gp/util.py",
line 37, in <module>

    from pymc.distributions.distribution import NoDistribution

  File
"/Users/Shared/anaconda3/envs/scTIGER/lib/python3.9/site-packages/pymc/distributions/__init__.py",
line 21, in <module>

    from pymc.distributions.bound import Bound

  File
"/Users/Shared/anaconda3/envs/scTIGER/lib/python3.9/site-packages/pymc/distributions/bound.py",
line 23, in <module>

    from pymc.distributions.continuous import BoundedContinuous,
bounded_cont_transform

  File
"/Users/Shared/anaconda3/envs/scTIGER/lib/python3.9/site-packages/pymc/distributions/continuous.py",
line 88, in <module>

    from pymc.distributions.distribution import DIST_PARAMETER_TYPES,
Continuous

  File
"/Users/Shared/anaconda3/envs/scTIGER/lib/python3.9/site-packages/pymc/distributions/distribution.py",
line 50, in <module>

    from pymc.printing import str_for_dist, str_for_symbolic_dist

  File
"/Users/Shared/anaconda3/envs/scTIGER/lib/python3.9/site-packages/pymc/printing.py",
line 25, in <module>

    from pymc.model import Model

  File
"/Users/Shared/anaconda3/envs/scTIGER/lib/python3.9/site-packages/pymc/model.py",
line 64, in <module>

    from pymc.initial_point import make_initial_point_fn

  File
"/Users/Shared/anaconda3/envs/scTIGER/lib/python3.9/site-packages/pymc/initial_point.py",
line 28, in <module>

    from pymc.util import get_transformed_name, get_untransformed_name,
is_transformed_name

  File
"/Users/Shared/anaconda3/envs/scTIGER/lib/python3.9/site-packages/pymc/util.py",
line 19, in <module>

    import arviz

  File
"/Users/Shared/anaconda3/envs/scTIGER/lib/python3.9/site-packages/arviz/__init__.py",
line 33, in <module>

    from .data import *

  File
"/Users/Shared/anaconda3/envs/scTIGER/lib/python3.9/site-packages/arviz/data/__init__.py",
line 2, in <module>

    from .base import CoordSpec, DimSpec, dict_to_dataset,
numpy_to_data_array

  File
"/Users/Shared/anaconda3/envs/scTIGER/lib/python3.9/site-packages/arviz/data/base.py",
line 11, in <module>

    import xarray as xr

  File
"/Users/Shared/anaconda3/envs/scTIGER/lib/python3.9/site-packages/xarray/__init__.py",
line 3, in <module>

    from xarray import testing, tutorial

  File
"/Users/Shared/anaconda3/envs/scTIGER/lib/python3.9/site-packages/xarray/testing.py",
line 11, in <module>

    from xarray.core.coordinates import Coordinates

  File
"/Users/Shared/anaconda3/envs/scTIGER/lib/python3.9/site-packages/xarray/core/coordinates.py",
line 16, in <module>

    from xarray.core.alignment import Aligner

  File
"/Users/Shared/anaconda3/envs/scTIGER/lib/python3.9/site-packages/xarray/core/alignment.py",
line 24, in <module>

    from xarray.core.variable import Variable, as_compatible_data,
calculate_dimensions

  File
"/Users/Shared/anaconda3/envs/scTIGER/lib/python3.9/site-packages/xarray/core/variable.py",
line 48, in <module>

    from xarray.namedarray.core import NamedArray

  File
"/Users/Shared/anaconda3/envs/scTIGER/lib/python3.9/site-packages/xarray/namedarray/core.py",
line 24, in <module>

    from xarray.namedarray._typing import (

  File
"/Users/Shared/anaconda3/envs/scTIGER/lib/python3.9/site-packages/xarray/namedarray/_typing.py",
line 28, in <module>

    _DType = TypeVar("_DType", bound=np.dtype[Any])

TypeError: 'numpy._DTypeMeta' object is not subscriptable

**Comment by chenyongrowan** [comment]
Hi! Yes, that is a numpy issue. Can you try ```conda update numpy```  in your scTIGER environment? 

I am currently working on setting up scTIGER as an Anaconda package, but may need a week or two to get everything set up correctly. Once that is complete, it should be much easier to download the package. Thanks for your patience as I work through this!

**Comment by utkarsh027** [comment]
When i am updating numpy it is showing compatibility issue with bambi.
Let me know when you have resolved the error.

Thank you

**Comment by chenyongrowan** [comment]
I am not sure why it is giving a compatibility issue, I can't recreate the error on my end. 

I have uploaded a very basic conda package to help set the package dependencies correctly. I updated our installation instructions to reflect this. I have not had a chance to test it on a CUDA capable machine yet, but it does work on CPU processing systems. I will test it on a CUDA capable machine later this week. 

Can you try the following and let me know if you are able to successfully install? 
```
conda create -n scTIGER 
conda activate scTIGER
conda install pytorch==2.1.2 torchvision torchaudio cpuonly==2.0 -c pytorch
conda install madison.dautle::sctiger
```

**Comment by utkarsh027** [comment]
I will do and let you know.

**Comment by chenyongrowan** [comment]
Hi! Due to the new package installation instructions and list of package dependencies from our operational installation of the package, we are going to resolve this issue. We hope you were able to install scTIGER!
