### ISSUE TITLE
Key error

### ISSUE THREAD

**Issue by gomeznick86** [chenyongrowan/scTIGER#2]
Hello! I'm interested in using your package and was able to install it correctly. However, running the sample data, and my own data causes the same key and to numeric error. It seems that it is having trouble finding the Gene name for the key and converting the relationships (I think thats what these are) to numerics. Ultimately, I'm able to produce the histogram but the graphml files are not generated. I've attached some screenshots for reference. 

Thanks in advance for your help, I'm excited about trying out your package!

Nick 
<img width="788" alt="Screenshot 2024-05-21 at 8 54 58 AM" src="https://github.com/chenyongrowan/scTIGER/assets/57917990/fff4b461-79b1-4775-a375-25da2f5f940c">
<img width="1045" alt="Screenshot 2024-05-21 at 8 55 27 AM" src="https://github.com/chenyongrowan/scTIGER/assets/57917990/182ee0ba-f04a-4091-962c-48922e1cf6d4">

**Comment by chenyongrowan** [comment]
Hi! Could you upload the raw count gene file from the first part of scTIGER? It should be in the output folder as [gene_name].csv ("AR.csv, PTEN.csv, etc.). 

I think the error is related to the read_csv in line 277 of scTIGER.py, potentially due to miniconda (I have only tested it using Anaconda3). I just want to make sure the output from the first part looks as it should before I dive into testing with miniconda. Thank you!

**Comment by gomeznick86** [comment]
Apologies I missed the above the comment. I'm working back to trying to get your package to work. I don't think its an issue of miniconda vs Anaconda3. It seems that whatever value its referencing is missing.  A screenshot of the csv is below. ERG and PTEN also show the same structure. 

<img width="446" alt="Screenshot 2024-08-06 at 8 35 17 AM" src="https://github.com/user-attachments/assets/98952f8a-67e0-4fc1-bd4f-b66d53dbf4f5">

**Comment by chenyongrowan** [comment]
Hi! 

One of the students in our lab ran into this issue as well, so I was finally able to find out what it was! It looks like the default behavior in reading or writing to csv files in the pandas module changed. What you're seeing is a lack of a column name to be selected by the program as a result. 

I have added a line of code to the package to hopefully resolve this issue. As it hasn't happened on my computers, I can't fully test the patch, but I hope that it resolves the issue. If not, we are planning to have scTIGER2.0 released in Spring/Summer 2025! That will have the same capability + additional features as scTIGER with a more thorough correction of the error, but the patch I pushed should work for now. Please let me know if it doesn't work!
