### ISSUE TITLE
installation issue for CUDA enabled setup

### ISSUE THREAD

**Issue by shrey9125** [chenyongrowan/scTIGER#3]
Hello, 
I am trying to run your method with CUDA enabled option. However, I am facing issues at the last step i.e., installing the sctiger package. It throws an error saying:

`(scTIGER) conda install -c madison.dautle sctiger
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: | 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                                                

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.17=0
  - feature:|@/linux-64::__glibc==2.17=0

Your installed version is: 2.17
` 

I checked the packages list but could not find this one, and thus raising the issue. 

_attachment: terminal output text file during installation_

[cleaned_output.docx](https://github.com/user-attachments/files/17360033/cleaned_output.docx)

**Comment by chenyongrowan** [comment]
Hi. Thanks for reaching out. You may have to update your conda installation. 

I looked through your terminal output and found that even when you specify pytorch-cuda=11.8, it is installing pytorch-cuda=11.7. You also will want to include the -c nvidia flag in that command. 

Conda isn't the best with error messages. Sometimes the errors arise from unlisted things. I believe that it is likely your conda version, but I am not fully sure. Please try updating your conda version and reinstalling. Let me know if any additional problems arise! I just test installed scTIGER with conda version 24.5.0 and it was able to successfully install and run. 

I'll mark this as resolved for now, but feel free to open it back up if that doesn't fix your installation error!
